services:
  mongodb:
    image: mongo:latest
    container_name: mongo-dev-microservices-oAuth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-microservices-oAuth
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  user-service:
    build:
      context: ./backend/services/user-service
      dockerfile: Dockerfile
    container_name: user-service-oAuth
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - USERS_API_HOST=${USERS_API_HOST}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-oAuth
    ports:
      - "5173:5173"
    environment:
      - VITE_USERS_API_HOST=${VITE_USERS_API_HOST}
      - VITE_NODE_ENV=${VITE_NODE_ENV}

volumes:
  mongo-data:
  mongo-config:
